name: Publish

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  pr-context:
    name: PR context
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ env.pr_branch }}
      commit: ${{ env.pr_sha }}
      pr_number: ${{ env.pr_number }}

    steps:
      - name: Get PR context
        uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe # v3.1.4
        id: pr_context
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: PR_context

      - name: Set PR context environment variables
        if: ${{ steps.pr_context.conclusion == 'success' }}
        run: |
          echo "pr_branch=$(cat PR_branch)" >> $GITHUB_ENV
          echo "pr_number=$(cat PR_number)" >> $GITHUB_ENV
          echo "pr_sha=$(cat PR_sha)" >> $GITHUB_ENV
